[package]
name = "fantoch_ps"
version = "0.1.0"
edition = "2018"

authors = ["Vitor Enes <vitorenesduarte@gmail.com>"]
license = "MIT/Apache-2.0"

[features]
amortize = ["fantoch/amortize"]
timing = ["fantoch/timing"]
parallel-sim = ["rayon"]

[dependencies]
ahash = "0.4.1"
clap = "2.33.1"
dashmap = "4.0.0-rc6"
futures = { version = "0.3.5", default-features = false, features = [] }
rand = "0.7.3"
rayon = { version = "1.3.1", optional = true }
serde = { version = "1.0.114", features = ["derive"] }
threshold = "0.8.9"
tokio = { version = "0.2.21", features = ["full", "parking_lot"] }
tracing = "0.1.16"
parking_lot = "0.11.0"
num_cpus = "1.13.0"

jemallocator = "0.3.2"

fantoch = { path = "../fantoch" }

[dev-dependencies]
permutator = "0.4.0"
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"

[[bin]]
name = "simulation"
required-features = ["parallel-sim"]
