[package]
name = "fantoch"
version = "0.1.0"
edition = "2018"

authors = ["Vitor Enes <vitorenesduarte@gmail.com>"]
license = "MIT/Apache-2.0"

[features]
default = []
amortize = ["griddle"]
prof = ["fantoch_prof"]

[dependencies]
ahash = "0.4.4"
bincode = "1.3.1"
bytes = "0.5.6"
flate2 = "1.0.16"
futures = { version = "0.3.5", default-features = false, features = ["alloc"] }
griddle = { version = "0.3.1", features = ["serde"], optional = true }
hashbrown = { version = "0.8.1", features = ["serde"] }
parking_lot = "0.11.0"
rand = "0.7.3"
serde = { version = "1.0.114", features = ["derive"] }
threshold = "0.8.9"
tokio = { version = "0.2.22", features = ["full", "parking_lot"] }
tokio-util = { version = "0.3.1", features = ["codec"] }
tracing = "0.1.17"
zipf = "6.1.0"

fantoch_prof = { path = "../fantoch_prof", optional = true }

[dev-dependencies]
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
