[package]
name = "fantoch_exp"
version = "0.1.0"
edition = "2018"

authors = ["Vitor Enes <vitorenesduarte@gmail.com>"]
license = "MIT/Apache-2.0"

# by default, run the main binary
default-run = "main"

[features]
default = ["exp"]
exp = ["futures", "rusoto_core", "rusoto_credential", "rusoto_ec2", "tracing", "tracing-futures", "tracing-subscriber", "tokio", "tsunami"]

[dependencies]
bincode = "1.3.1"
color-eyre = "0.5.1"
indicatif = "0.15.0"
flate2 = "1.0.17"
futures = { version = "0.3.5", default-features = false, features = [], optional = true }
rusoto_core = { version = "0.45.0", optional = true }
rusoto_credential = { version = "0.45.0", optional = true }
rusoto_ec2 = { version = "0.45.0", optional = true }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
tracing = { version = "0.1.19", optional = true }
tracing-futures = { version = "0.2.4", optional = true }
tracing-subscriber = { version = "0.2.11", optional = true }
tokio = { version = "0.2.22", features = ["time"], optional = true }
tsunami = { version = "0.11.0-beta.9", default-features = false, features = ["aws", "baremetal"], optional = true }

fantoch = { path = "../fantoch" }

[[bin]]
name = "main"
required-features = ["exp"]

[[bin]]
name = "ping"
required-features = ["exp"]
