name: Continuous integration

on: [push, pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-06-10
          override: true

      - name: Test fantoch_prof
        run: cd fantoch_prof/ && cargo test
        env:
          QUICKCHECK_TESTS: '10000'
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort'
          RUSTDOCFLAGS: '-Cpanic=abort'
        timeout-minutes: 60

      - name: Test fantoch
        run: cd fantoch/ && cargo test --features prof
        env:
          QUICKCHECK_TESTS: '10000'
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort'
          RUSTDOCFLAGS: '-Cpanic=abort'
        timeout-minutes: 60

      - name: Test fantoch_ps
        run: cd fantoch_ps/ && cargo test
        env:
          QUICKCHECK_TESTS: '10000'
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort'
          RUSTDOCFLAGS: '-Cpanic=abort'
        timeout-minutes: 60

      - name: Test fantoch_bote
        run: cd fantoch_bote/ && cargo test
        env:
          QUICKCHECK_TESTS: '10000'
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort'
          RUSTDOCFLAGS: '-Cpanic=abort'
        timeout-minutes: 60

      - name: Test fantoch_plot
        run: |
          sudo apt-get install python3-dev python3-pip
          pip3 install matplotlib
          cd fantoch_plot/ && cargo test
        env:
          QUICKCHECK_TESTS: '10000'
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort'
          RUSTDOCFLAGS: '-Cpanic=abort'
        timeout-minutes: 60

      - name: Check fantoch_exp
        run: cd fantoch_exp/ && cargo check

      - name: Test feature combinations
        run: |
          cargo install cargo-hack
          cargo hack check --feature-powerset --no-dev-deps

      - name: Coverage
        uses: actions-rs/grcov@v0.1
        with:
          config: .github/grcov.yml

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info
          base-path: ./

      - name: Slack (success)
        uses: rtCamp/action-slack-notify@v2.0.2
        if: ${{ success() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: dev-ci
          SLACK_COLOR: '#5F9744'
          SLACK_ICON: https://avatars1.githubusercontent.com/u/44036562?s=48
          SLACK_TITLE: CI success
          SLACK_USERNAME: CI

      - name: Slack (failure)
        uses: rtCamp/action-slack-notify@v2.0.2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: dev-ci
          SLACK_COLOR: '#B94947'
          SLACK_ICON: https://avatars1.githubusercontent.com/u/44036562?s=48
          SLACK_TITLE: CI failure
          SLACK_USERNAME: CI
